# Generated by Django 5.0.3 on 2024-03-19 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='special_request',
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='reservation',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
    ]
