# Generated by Django 5.0.3 on 2024-03-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
