# Generated by Django 5.0.3 on 2024-03-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_table_table_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialrequest',
            old_name='request_text',
            new_name='content',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
        migrations.AlterModelTable(
            name='specialrequest',
            table='special_request',
        ),
        migrations.AlterModelTable(
            name='table',
            table='table',
        ),
    ]
