# Generated by Django 5.0.3 on 2024-03-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_reservation_customer_alter_reservation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table_location',
            field=models.CharField(choices=[('Garden', 'Garden'), ('Bar', 'Bar'), ('Dining Room', 'Dining Room')], default='GARDEN', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='table_location',
            field=models.CharField(choices=[('Garden', 'Garden'), ('Bar', 'Bar'), ('Dining Room', 'Dining Room')], max_length=50),
        ),
    ]
