# Generated by Django 5.0.3 on 2024-03-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Meze', 'Meze'), ('Salad', 'Salad'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert'), ('Beverage', 'Beverage'), ('Pide', 'Pide'), ('Steak', 'Steak'), ('Other', 'Other')], max_length=50),
        ),
    ]
