# Generated by Django 5.0.3 on 2024-03-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menuitem',
            table='menu',
        ),
    ]
