# Generated by Django 5.0.3 on 2024-03-26 17:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
