# Generated by Django 5.0.3 on 2024-03-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_menu_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_image',
            new_name='image',
        ),
    ]
